version: '3.8'

services:
  backend:
    container_name: nestmates-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: npm run dev
