version: '3.8'

services:
  backend:
    container_name: nestmates-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/docker-backend
      - /docker-backend/node_modules
    ports:
      - "5001:5001"
