version: '3.8'

services:
  backend:
    container_name: htn_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/docker-backend
      - /docker-backend/node_modules
    ports:
      - "5000:5000"
    command: npm run dev